name = "alice"
version = "0.1.5-dev"
description = "Adventures for Learning and Inspiring Coding Excellence"
website = "https://github.com/rocher/Alice/wiki"
licenses = "MIT"
tags = [
   "alice",
   "adventures",
   "learning",
   "mathematics",
   "problems",
   "challenges",
]

authors = ["Francesc Rocher"]
maintainers = ["Francesc Rocher <francesc.rocher@gmail.com>"]
maintainers-logins = ["rocher"]

[build-profiles]
"alice" = "release"

[build-switches."*"]
ada_version = ["-gnat2022", "-gnatX"]

[[depends-on]]
clic = "~0.2.1"
simple_logging = "^1.2.0"

[origin]
commit = "62aab5afa049d6015ef87952dcbed7009dd12980"
url = "git+https://github.com/alice-adventures/Alice.git"

